routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('home');
Route::get('/home2', 'PageController@index2')->name('home2');
Route::get('/about', 'PageController@about')->name('about');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::get('/search', 'SearchController@search')->name('search');
Route::get('/search/{search}/{unsetKeyword}', 'SearchController@unsetKeyword')->name('search.unsetKeyword');
Route::get('/json/companies.json', 'SearchController@jsonCompanies')->name('search.companies.json');


Route::prefix('login')->group(function () {
    Route::post('/', 'LoginController@index')->name('login.post');
    Route::get('register', 'LoginController@register')->name('login.register');
    Route::get('forgot', 'LoginController@forgot')->name('login.forgot');
    Route::post('forgot', 'LoginController@postForgot')->name('login.forgot.post');
    Route::get('reset/{email}/{token}', 'LoginController@reset')->name('login.reset');
    Route::post('reset/{email}/{token}', 'LoginController@postReset')->name('login.reset.post');
    Route::post('register', 'LoginController@postRegister')->name('login.register.post');
    Route::get('logout', 'LoginController@logout')->name('login.logout');
    Route::get('facebook', 'LoginController@redirectToFacebook')->name('login.facebook');
    Route::get('facebook/callback', 'LoginController@handleProviderCallback')->name('login.facebook.redirect');
});

Route::prefix('blog')->group(function(){
    Route::get('/', 'BlogController@index')->name('blog.index');
    Route::get('{slug}', 'BlogController@show')->name('blog.show');
    Route::post('{slug}', 'BlogController@postComment')->name('blog.comment.post');
});

Route::prefix('admin')->middleware('admin')->as('admin.')->group(function () {
    Route::get('/', 'Admin\PageController@index')->name('index');
    Route::resource('users', 'Admin\UserController');

    Route::prefix('blog')->as('blog.')->group(function () {
        Route::resource('articles', 'Admin\Blog\ArticleController');
        Route::resource('categories', 'Admin\Blog\CategoryController');
        Route::resource('tags', 'Admin\Blog\TagController');
        Route::resource('comments', 'Admin\Blog\CommentController')->except('create', 'store');
    });

    Route::prefix('categorization')->as('categorization.')->group(function () {
        Route::resource('domains', 'Admin\Categorization\DomainController')->except('show');
        Route::resource('activity_areas', 'Admin\Categorization\ActivityAreaController')->except('show');
    });

    Route::prefix('industry')->as('industry.')->group(function () {
        Route::resource('companies', 'Admin\Industry\CompanyController');
        Route::resource('comments', 'Admin\Industry\CommentController');
    });

    Route::prefix('question')->as('question.')->group(function () {
        Route::resource('domains', 'Admin\Question\DomainController');
        Route::resource('activity_areas', 'Admin\Question\ActivityAreaController');
    });

    Route::get('algorithme', 'Admin\PageController@algorithme')->name('algorithme');
    Route::post('algorithme', 'Admin\PageController@postAlgorithme')->name('algorithme.post');

    Route::resource('icons', 'Admin\IconController')->except('show');

    Route::prefix('json')->as('json.')->group(function () {
        Route::get('tags', 'Admin\Blog\TagController@json')->name('tags');
        Route::get('wikipedia/{object}', 'Admin\PageController@wikipediaApi')->name('wikiApi');
    });

});

app/Models/Categorization/Domain.php
<?php

namespace App\Models\Categorization;

use Illuminate\Database\Eloquent\Model;

class Domain extends Model
{
    const TOP_DOMAINS = [
        1 => 'Santé',
        2 => 'Ecologie',
        3 => 'Ressources humaines',
        4 => 'Economie',
        5 => 'Production'
    ];

    const DOMAIN_COLORS = [
        1 => 'danger',
        2 => 'success',
        3 => 'info',
        4 => 'warning',
        5 => 'primary'
    ];

    protected $fillable = ['name', 'coefficient', 'parent'];

    public function parent(){
        return self::TOP_DOMAINS[$this->parent];
    }

    public function color(){
        return self::DOMAIN_COLORS[$this->parent];
    }
}

app/Models/Question/ActivityArea.php
<?php

namespace App\Models\Question;

use Illuminate\Database\Eloquent\Model;

class ActivityArea extends Model
{
    protected $table = 'activity_area_questions';

    public function activityArea(){
        return $this->belongsTo(\App\Models\Categorization\ActivityArea::class);
    }
}

app/Models/Question/Domain.php
<?php

namespace App\Models\Question;

use Illuminate\Database\Eloquent\Model;

class Domain extends Model
{
    protected $table = 'domain_questions';

    public function domain(){
        return $this->belongsTo(\App\Models\Categorization\Domain::class);
    }
}

app/Http/Controllers/Admin/Categorization/DomainController.php
<?php

namespace App\Http\Controllers\Admin\Categorization;

use App\Models\Categorization\Domain;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DomainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $domains = Domain::all();
        return view('back.categorization.domains.index', compact('domains'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('back.categorization.domains.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'coefficient' => 'required|between:0,100',
            'parent' => 'required|between:1,5'
        ]);

        $domain = new Domain($request->input());
        $domain->save();

        return redirect()->route('admin.categorization.domains.index')->with('adminCategorizationDomainCreatedSuccess', true);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function show(Domain $domain)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function edit(Domain $domain)
    {
        return view('back.categorization.domains.edit', compact('domain'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Domain $domain)
    {
        $request->validate([
            'name' => 'required',
            'coefficient' => 'required|between:0,100',
            'parent' => 'required|between:1,5'
        ]);

        $domain->update($request->input());

        return redirect()->route('admin.categorization.domains.index')->with('adminCategorizationDomainCreatedSuccess', true);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function destroy(Domain $domain)
    {
        $domain->delete();
        return redirect()->back()->with('adminCategorizationDomainDeletedSuccess', true);
    }
}

app/Http/Controllers/Admin/Question/ActivityAreaController.php
<?php

namespace App\Http\Controllers\Admin\Question;

use App\Models\Question\ActivityArea;
use App\Service\Form;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActivityAreaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = ActivityArea::all();
        return view('back.question.activity_areas.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Form $form)
    {
        $activityAreas = $form->generateTree(\App\Models\Categorization\ActivityArea::class);
        return view('back.question.activity_areas.create', compact('activityAreas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'question' => 'required',
            'coefficient' => 'required|between:0,100',
            'activityArea' => 'required|exists:activity_areas,id'
        ]);

        $question = new ActivityArea();
        $question->question = $request->input('question');
        $question->activity_area_id = $request->input('activityArea');
        $question->coefficient = $request->input('coefficient');
        if($request->has('direction') && !empty($request->input('direction'))){
            $question->direction = 1;
        }else{
            $question->direction = -1;
        }

        $question->save();

        return redirect()->route('admin.question.activity_areas.index')->with('adminQuestionActivityAreaCreatedSuccess', true);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Question\ActivityArea  $activityArea
     * @return \Illuminate\Http\Response
     */
    public function show(ActivityArea $activityArea)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Question\ActivityArea  $activityArea
     * @return \Illuminate\Http\Response
     */
    public function edit(ActivityArea $activityArea, Form $form)
    {
        $activityAreas = $form->generateTree(\App\Models\Categorization\ActivityArea::class);
        return view('back.question.activity_areas.edit', compact('activityAreas', 'activityArea'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Question\ActivityArea  $activityArea
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ActivityArea $activityArea)
    {
        $request->validate([
            'question' => 'required',
            'coefficient' => 'required|between:0,100',
            'activityArea' => 'required|exists:activity_areas,id'
        ]);

        $activityArea->question = $request->input('question');
        $activityArea->activity_area_id = $request->input('activityArea');
        $activityArea->coefficient = $request->input('coefficient');
        if($request->has('direction') && !empty($request->input('direction'))){
            $activityArea->direction = 1;
        }else{
            $activityArea->direction = -1;
        }

        $activityArea->save();

        return redirect()->route('admin.question.activity_areas.index')->with('adminQuestionActivityAreaUpdatedSuccess', true);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Question\ActivityArea  $activityArea
     * @return \Illuminate\Http\Response
     */
    public function destroy(ActivityArea $activityArea)
    {
        $activityArea->delete();
        return redirect()->back()->with('adminQuestionActivityAreaDeletedSuccess', true);
    }
}

app/Http/Controllers/Admin/Question/DomainController.php
<?php

namespace App\Http\Controllers\Admin\Question;

use App\Models\Question\Domain;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DomainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Domain::all();
        return view('back.question.domains.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $domains = \App\Models\Categorization\Domain::all()->pluck('name', 'id');
        return view('back.question.domains.create', compact('domains'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'question' => 'required',
            'coefficient' => 'required|between:0,100',
            'domain' => 'required|numeric'
        ]);

        $domainQuestion = new Domain();
        $domainQuestion->question = $request->input('question');
        $domainQuestion->domain_id = $request->input('domain');
        $domainQuestion->coefficient = $request->input('coefficient');
        if($request->has('direction') && !empty($request->input('direction'))){
            $domainQuestion->direction = 1;
        }else{
            $domainQuestion->direction = -1;
        }

        $domainQuestion->save();

        return redirect()->route('admin.question.domains.index')->with('adminQuestionDomainCreatedSuccess', true);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Question\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function show(Domain $domain)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Question\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function edit(Domain $domain)
    {
        $domains = \App\Models\Categorization\Domain::all()->pluck('name', 'id');
        return view('back.question.domains.edit', compact('domains', 'domain'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Question\Domain  $domainQuestion
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Domain $domain)
    {
        $request->validate([
            'question' => 'required',
            'coefficient' => 'required|between:0,100',
            'domain' => 'required|numeric'
        ]);

        $domain->question = $request->input('question');
        $domain->domain_id = $request->input('domain');
        $domain->coefficient = $request->input('coefficient');
        if($request->has('direction') && !empty($request->input('direction'))){
            $domain->direction = 1;
        }else{
            $domain->direction = -1;
        }

        $domain->save();

        return redirect()->route('admin.question.domains.index')->with('adminQuestionDomainUpdatedSuccess', true);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Question\Domain  $domain
     * @return \Illuminate\Http\Response
     */
    public function destroy(Domain $domain)
    {
        $domain->delete();
        return redirect()->back()->with('adminQuestionDomainDeletedSuccess', true);
    }
}

resources/views/back/question/domains/create.blade.php
@extends('back.layout.default', ['navLink' => 'question.domains'])

@section('title', 'Créer une question de domaine')

@section('header')
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><span class="font-weight-semibold">Créer une question de domaine</span></h4>
        </div>
    </div>
@endsection
@section('content')

    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Créer une question de domaine</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            Créer une <code>question</code> est très simple, il suffit de d'entrér la question et indiquer un coeeficient !
        <hr>
        {!! BootForm::open(['url' => route('admin.question.domains.store')]) !!}
            {!! BootForm::select('domain', 'Domaine', $domains) !!}
            <a class="btn btn-sm btn-outline-primary" target="_blank" href="{{ route('admin.categorization.domains.create') }}">Créer un domaine</a>
            <hr>
            {!! BootForm::textarea('question', false, null, ['placeholder' => 'Entrer une question']) !!}
            {!! BootForm::text('coefficient', 'Coefficient (en %)', 50, ['class' => 'touchspin-postfix']) !!}
            <div class="form-check form-check-switch form-check-switch-left">
                <label class="form-check-label d-flex align-items-center">
                    <input type="checkbox" data-on-color="success" data-off-color="danger" data-on-text="Positive" data-off-text="Négative" class="form-check-input-switch" name="direction" @if(empty(old('title') and empty(old('published'))) or !empty(old('published') and old('published') == 'on'))) checked @endif>
                </label>
            </div>
            <hr>
            <div class="text-right">
                <button type="submit" class="btn btn-lg btn-primary">Créer</button>
            </div>
        {!! BootForm::close() !!}
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/inputs/touchspin.min.js') }}"></script>
    <script type="text/javascript">
      $( document ).ready(function() {
        $('.select-search').select2();
        $('.touchspin-postfix').TouchSpin({
          min: 0,
          max: 100,
          step: 0.1,
          decimals: 2,
          postfix: '%'
        });
      });
    </script>
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/styling/switch.min.js') }}"></script>
    <script type="text/javascript">
      $( document ).ready(function() {
        $('.form-check-input-switch').bootstrapSwitch();
      });
    </script>
@endsection

resources/views/back/question/domains/edit.blade.php
@extends('back.layout.default', ['navLink' => 'question.domains'])

@section('title', 'Modifier une question de domaine')

@section('header')
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><span class="font-weight-semibold">Modifier une question de domaine</span></h4>
        </div>
    </div>
@endsection
@section('content')

    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Créer une question de domaine</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            Modifier une <code>question</code> est très simple, il suffit de d'entrér la question et indiquer un coefficient !
            <hr>
            {!! BootForm::open(['url' => route('admin.question.domains.update', $domain), 'method' => 'PUT', 'model' => $domain]) !!}
            {!! BootForm::select('domain', 'Domaine', $domains) !!}
            <a class="btn btn-sm btn-outline-primary" target="_blank" href="{{ route('admin.categorization.domains.create') }}">Créer un domaine</a>
            <hr>
            {!! BootForm::textarea('question', false, null, ['placeholder' => 'Entrer une question']) !!}
            {!! BootForm::text('coefficient', 'Coefficient (en %)', null, ['class' => 'touchspin-postfix']) !!}
            <div class="form-check form-check-switch form-check-switch-left">
                <label class="form-check-label d-flex align-items-center">
                    @if($errors->any())
                        <input type="checkbox" data-on-color="success" data-off-color="danger" data-on-text="Positive" data-off-text="Négative" class="form-check-input-switch" name="direction" @if(!empty(old('direction'))) checked @endif>
                    @else
                        <input type="checkbox" data-on-color="success" data-off-color="danger" data-on-text="Positive" data-off-text="Négative" class="form-check-input-switch" name="direction" @if($domain->direction == 1) checked @endif>
                    @endif
                </label>
            </div>
            <hr>
            <div class="text-right">
                <button type="submit" class="btn btn-lg btn-primary">Modifier</button>
            </div>
            {!! BootForm::close() !!}
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/inputs/touchspin.min.js') }}"></script>
    <script type="text/javascript">
      $( document ).ready(function() {
        $('#cssClass').on('input', function() {
          $('#iconPreview').attr('class', $('#cssClass').val());
        });
        $('.touchspin-postfix').TouchSpin({
          min: 0,
          max: 100,
          step: 0.1,
          decimals: 2,
          postfix: '%'
        });
      });
    </script>
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/styling/switch.min.js') }}"></script>
    <script type="text/javascript">
      $( document ).ready(function() {
        $('.form-check-input-switch').bootstrapSwitch();
      });
    </script>
@endsection

resources/views/back/question/domains/index.blade.php
@extends('back.layout.default', ['navLink' => 'question.domains'])

@section('title', 'Questions relatives aux différent domaines')

@section('header')
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><span class="font-weight-semibold">Questions relatives aux différents domaines</span></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        <div class="header-elements d-none text-center text-md-left mb-3 mb-md-0">
            <a href="{{ route('admin.question.domains.create') }}" class="btn bg-danger-400"><i class="fa fa-plus-circle"></i> Créer une question</a>
        </div>
    </div>
@endsection
@section('content')

    @if(Session::has('adminQuestionDomainDeletedSuccess'))
        <div class="alert bg-success text-white alert-styled-right alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
            <span class="font-weight-semibold">Super!</span> Cette question n'existe maintenant plus !
        </div>
    @elseif(Session::has('adminQuestionDomainUpdatedSuccess'))
        <div class="alert bg-success text-white alert-styled-right alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
            <span class="font-weight-semibold">Super!</span> Vous venez de mettre à jour cette question
        </div>
    @endif

    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Liste des questions</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            Les <code>Questions</code> sont affichés ici, en cliquant sur le petit bouton à droite tu pourras directement les gèrer. Pour l'instant les options disponibles sont :  <code>ajouter</code>, <code>modifier</code> et <code>supprimer</code> !
            <br>
            <br>
            @foreach(\App\Models\Categorization\Domain::TOP_DOMAINS as $key => $domain)
                <button class="btn btn-sm btn-{{ \App\Models\Categorization\Domain::DOMAIN_COLORS[$key] }}">{{ $domain }}</button>
            @endforeach
        </div>

        <table class="table datatableItems">
            <thead>
            <tr>
                <th>Question</th>
                <th>Coefficient</th>
                <th>Sens</th>
                <th>Domaine</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($questions as $tableQuestion)
                <tr>
                    <td class="w-75">{{ $tableQuestion->question }}</td>
                    <td>{{ $tableQuestion->coefficient }}%</td>
                    <td>
                        @if($tableQuestion->direction === 1)
                            <button class="btn btn-sm btn-success">Positif</button>
                        @elseif($tableQuestion->direction === -1)
                            <button class="btn btn-sm btn-danger">Négatif</button>
                        @else
                            <button class="btn btn-sm btn-secondary">?</button>
                        @endif
                    </td>
                    <td><a href="{{ route('admin.categorization.domains.edit', $tableQuestion->domain) }}" class="btn btn-xs btn-{{ $tableQuestion->domain->color() }}">{{ $tableQuestion->domain->name }}</a></td>
                    <td class="text-center">
                        <div class="list-icons">
                            <div class="dropdown">
                                <a href="#" class="list-icons-item" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="{{ route('admin.question.domains.edit', $tableQuestion) }}" class="dropdown-item"><i class="icon-pencil4"></i> Modifier</a>
                                    <a data-toggle="modal" data-target="#modalDeleteDomainQuestion" onClick="deleteDomainQuestion({{ $tableQuestion->id }})" href="javascript:void(0)" class="dropdown-item"><i class="icon-trash"></i> Supprimer</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div id="modalDeleteDomainQuestion" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h5 class="modal-title"><i class="icon-trash"></i> &nbsp;Supprimer une question</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <div class="modal-body">
                    <div class="alert alert-danger alert-dismissible alert-styled-left border-top-0 border-bottom-0 border-right-0">
                        <span class="font-weight-semibold">Attention!</span> Vous ne pourrez pas revenir en arrière.
                        <button type="button" class="close" data-dismiss="alert">×</button>
                    </div>

                    <h6 class="font-weight-semibold"><i class="icon-info3 mr-2"></i> Suppresion de la question</h6>
                    <p>En supprimant cette question, toutes les données relatives à celle-ci seront perdues</p>

                    <hr>
                </div>

                <div class="modal-footer">
                    <button class="btn btn-link" data-dismiss="modal"><i class="icon-cross2 font-size-base mr-1"></i> Annuler</button>
                    {!! BootForm::open(['method' => 'DELETE']) !!}
                    <button class="btn bg-danger"><i class="icon-checkmark3 font-size-base mr-1"></i> Supprimer</button>
                    {!! BootForm::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('admin_assets/js/pages/datatablesDefault.js') }}"></script>
    <script type="text/javascript">
        function deleteDomainQuestion(id){
            $('#modalDeleteDomainQuestion form').attr('action', '{{ route('admin.question.domains.index') }}/'+id);
        }
    </script>
@endsection