routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('home');
Route::get('/home2', 'PageController@index2')->name('home2');
Route::get('/about', 'PageController@about')->name('about');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::get('/search', 'SearchController@search')->name('search');
Route::get('/search/{search}/{unsetKeyword}', 'SearchController@unsetKeyword')->name('search.unsetKeyword');
Route::get('/json/companies.json', 'SearchController@jsonCompanies')->name('search.companies.json');


Route::prefix('login')->group(function () {
    Route::post('/', 'LoginController@index')->name('login.post');
    Route::get('register', 'LoginController@register')->name('login.register');
    Route::get('forgot', 'LoginController@forgot')->name('login.forgot');
    Route::post('forgot', 'LoginController@postForgot')->name('login.forgot.post');
    Route::get('reset/{email}/{token}', 'LoginController@reset')->name('login.reset');
    Route::post('reset/{email}/{token}', 'LoginController@postReset')->name('login.reset.post');
    Route::post('register', 'LoginController@postRegister')->name('login.register.post');
    Route::get('logout', 'LoginController@logout')->name('login.logout');
    Route::get('facebook', 'LoginController@redirectToFacebook')->name('login.facebook');
    Route::get('facebook/callback', 'LoginController@handleProviderCallback')->name('login.facebook.redirect');
});

Route::prefix('blog')->group(function(){
    Route::get('/', 'BlogController@index')->name('blog.index');
    Route::get('{slug}', 'BlogController@show')->name('blog.show');
    Route::post('{slug}', 'BlogController@postComment')->name('blog.comment.post');
});

Route::prefix('admin')->middleware('admin')->as('admin.')->group(function () {
    Route::get('/', 'Admin\PageController@index')->name('index');
    Route::resource('users', 'Admin\UserController');

    Route::prefix('blog')->as('blog.')->group(function () {
        Route::resource('articles', 'Admin\Blog\ArticleController');
        Route::resource('categories', 'Admin\Blog\CategoryController');
        Route::resource('tags', 'Admin\Blog\TagController');
        Route::resource('comments', 'Admin\Blog\CommentController')->except('create', 'store');
    });

    Route::prefix('categorization')->as('categorization.')->group(function () {
        Route::resource('domains', 'Admin\Categorization\DomainController')->except('show');
        Route::resource('activity_areas', 'Admin\Categorization\ActivityAreaController')->except('show');
    });

    Route::prefix('industry')->as('industry.')->group(function () {
        Route::resource('companies', 'Admin\Industry\CompanyController');
        Route::resource('comments', 'Admin\Industry\CommentController');
    });

    Route::prefix('question')->as('question.')->group(function () {
        Route::resource('domains', 'Admin\Question\DomainController');
        Route::resource('activity_areas', 'Admin\Question\ActivityAreaController');
    });

    Route::get('algorithme', 'Admin\PageController@algorithme')->name('algorithme');
    Route::post('algorithme', 'Admin\PageController@postAlgorithme')->name('algorithme.post');

    Route::resource('icons', 'Admin\IconController')->except('show');

    Route::prefix('json')->as('json.')->group(function () {
        Route::get('tags', 'Admin\Blog\TagController@json')->name('tags');
        Route::get('wikipedia/{object}', 'Admin\PageController@wikipediaApi')->name('wikiApi');
    });

});

app/Models/Industry/Comment.php
<?php

namespace App\Models\Industry;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $table = 'company_comments';

    protected $fillable = ['username', 'website', 'email', 'content'];

    public function company(){
        return $this->belongsTo('App\Models\Industry\Company');
    }

    public function user(){
        return $this->belongsTo('App\Models\User');
    }
}

app/Models/Industry/Company.php
<?php

namespace App\Models\Industry;

use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Boolean;

class Company extends Model
{
    protected $fillable = ['name', 'parent_id', 'good_observation', 'avg_observation', 'bad_observation'];

    private $imagePath = 'uploads/company';

    public function parent(){
        return $this->belongsTo('App\Models\Industry\Company');
    }

    public function getTree(){
        $tree = [];
        $company = $this;
        while($company->parent != null){
            $company = $company->parent;
            $tree[] = $company;
        }
        return array_reverse($tree);
    }

    public function comments(){
        return $this->hasMany(Comment::class);
    }

    public function isHolding() : bool{
        return Company::where('parent_id', $this->id)->exists();
    }

    public function getImage(){
        return url($this->imagePath.'/'.$this->image);
    }

}

app/Http/Controllers/Admin/Industry/CommentController.php
<?php

namespace App\Http\Controllers\Admin\Industry;

use App\Models\Industry\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comments = Comment::all();
        return view('back.industry.comments.index', compact('comments'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Industry\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Industry\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        return view('back.industry.comments.edit', compact('comment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        $request->validate([
            'username' => 'nullable',
            'email' => 'nullable|email',
            'website' => 'nullable|url',
            'content' => 'required'
        ]);

        $comment->update($request->input());

        return redirect()->route('admin.industry.comments.index')->with('adminIndustryCommentUpdatedSuccess', true);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Industry\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();
        return redirect()->back()->with('adminIndustryCommentDeletedSuccess', true);
    }
}

app/Http/Controllers/Admin/Industry/CompanyController.php
<?php

namespace App\Http\Controllers\Admin\Industry;

use App\Models\Industry\Company;
use App\Service\Wikipedia;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();
        return view('back.industry.companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();
        return view('back.industry.companies.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'image' => 'required|image|max:2048',
            'good_observation' => 'nullable',
            'avg_observation' => 'nullable',
            'bad_observation' => 'nullable',
            'parent_id' => 'nullable'
        ]);

        $company = new Company($request->input());

        $imageName = 'ic_'.str_random(rand(10, 23)).'.png';
        Image::make($request->file('image'))->save('uploads/company/'.$imageName);
        $company->image = $imageName;

        if($request->has('infoNames') && $request->has('infoDatas')){
            $infos = array_combine($request->input('infoNames'), $request->input('infoDatas'));
            foreach ($infos as $k => $info) {
                if (empty($k) or empty($info)) unset($infos[$k]);
            }
        }else{
            $infos = [];
        }

        $company->infos = json_encode($infos);

        if($request->has('shareHolders')){
            $shareHolders = $request->input('shareHolders');
            foreach ($shareHolders as $k => $shareHolder){
                if(empty($shareHolder)) unset($shareHolders[$k]);
            }

        }else{
            $shareHolders = [];
        }
        $company->shareHolders = json_encode($shareHolders);

        $company->save();

        return redirect()->route('admin.industry.companies.index')->with('adminInsdustryCompaniesCreatedSuccess', true);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Industry\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        $companies =  Company::where('parent_id', $company->id)->get();
        return view('back.industry.companies.index', compact('companies', 'company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Industry\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        $companies = Company::all();
        return view('back.industry.companies.edit', compact('company', 'companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Industry\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        $request->validate([
            'name' => 'required',
            'image' => 'image|max:2048|nullable',
            'good_observation' => 'nullable',
            'avg_observation' => 'nullable',
            'bad_observation' => 'nullable',
            'parent_id' => 'nullable'
        ]);

        if($request->has('infoNames') && $request->has('infoDatas')){
            $infos = array_combine($request->input('infoNames'), $request->input('infoDatas'));
            foreach ($infos as $k => $info){
                if(empty($k) or empty($info)) unset($infos[$k]);
            }
        }else{
            $infos = [];
        }
        $company->infos = json_encode($infos);

        if($request->has('shareHolders')){
            $shareHolders = $request->input('shareHolders');
            foreach ($shareHolders as $k => $shareHolder){
                if(empty($shareHolder)) unset($shareHolders[$k]);
            }
        }else{
            $shareHolders = [];
        }
        $company->shareHolders = json_encode($shareHolders);

        if($request->hasFile('image')){
            Storage::delete($company->getImage());
            $imageName = 'ic_'.str_random(rand(10, 23)).'.png';
            Image::make($request->file('image'))->save('uploads/company/'.$imageName);
            $company->image = $imageName;
        }

        $company ->update($request->input());
        $company->save();

        return redirect()->route('admin.industry.companies.index')->with('adminInsdustryCompaniesUpdatedSuccess', true);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Industry\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();
        return redirect()->back()->with('adminInsdustryCompaniesDeletedSuccess', true);
    }
}

resources/views/back/industry/companies/create.blade.php
@extends('back.layout.default', ['navLink' => 'industry.companies'])

@section('title', 'Créer une entreprise')

@section('header')
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><span class="font-weight-semibold">Créer une entreprise</span></h4>
        </div>
    </div>
@endsection
@section('content')
    {!! BootForm::open(['enctype' => 'multipart/form-data', 'url' => route('admin.industry.companies.store')]) !!}
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Créer une entreprise</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            Créer une <code>Entreprise</code> est relativement simple ! Il suffit juste de remplir le formulaire.
        <hr>
            {!! BootForm::text('name', false, null, ['placeholder' => 'Nom de l\'entreprise']) !!}
            <div class="form-group ">
                <select class="form-control select-search" data-fouc name="parent_id">
                    <option value="">Aucune Holding</option>
                    @foreach($companies as $company)
                        <option value="{{ $company->id }}">{{ $company->name }}</option>
                    @endforeach
                </select>
            </div>
            {!! BootForm::textarea('good_observation', false, null, ['placeholder' => 'Bonne observation']) !!}
            {!! BootForm::textarea('avg_observation', false, null, ['placeholder' => 'Observation Moyenne']) !!}
            {!! BootForm::textarea('bad_observation', false, null, ['placeholder' => 'Mauvaise observation']) !!}
        </div>
    </div>

    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Image</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            {!! BootForm::file('image', false, ['placeholder' => 'Logo de l\entreprise']) !!}
        </div>
    </div>

    <div class="card infos">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Informations sur l'entreprise</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="tools">
                <a class="btn btn-info text-white" data-toggle="modal" data-target="#wikipediaModal"><i class="fa fa-upload"></i> Charger des informations Wikipédia</a>
                <a class="btn btn-danger text-white" onclick="addInfo()"><i class="icon-add"></i> Ajouter une information</a>
            </div>
            <div class="infoBox" style="margin-top: 25px">

            </div>
        </div>
    </div>

    <div class="card infos">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Actionnaires</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="tools">
                <a class="btn btn-danger text-white" onclick="addShareHolder()"><i class="icon-add"></i> Ajouter un actionnaire</a>
            </div>
            <div class="shareHolderBox" style="margin-top: 25px">

            </div>
        </div>
    </div>

    <div class="text-right">
        <button type="submit" class="btn btn-lg btn-primary">Créer</button>
    </div>
    {!! BootForm::close() !!}
    <div class="modal fade" id="wikipediaModal" tabindex="-1" role="dialog" aria-labelledby="wikipediaModalTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="wikipediaModal">Charger des informations Wikipédia</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group ">
                        <div>
                            <input placeholder="Titre de la page" class="form-control" id="wikipedia" name="wikipedia" type="text">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                    <button type="button" class="btn btn-primary" id="loadData">Charger</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/inputs/typeahead/typeahead.bundle.min.js') }}"></script>
    <script type="text/javascript">

        var cptInfo = 0;
        var cptShareHolder = 0;

        function deleteInfo(id){
          $('#info'+id).parent().parent().remove();
        }

        function addInfo(name = "", value=""){
          cptInfo++;
          $('.infoBox').append(
            '<div class="form-group row">' +
            '<div class="col-sm-11">' +
            '<label><input type="text" name="infoNames[]" class="form-control" placeholder="Nom de l\'information" value="'+ name +'"></label>' +
            '<textarea cols="50" rows="10" class="form-control" name="infoDatas[]" id="info'+ cptInfo +'">' + value + '</textarea>' +
            '</div>' +
            '<div class="col-md-1 text-danger" style="position: relative"><span onclick="deleteInfo('+ cptInfo +')" style=" position: absolute;top: 50%;transform: translateY(-50%); cursor: pointer"><i class="fa fa-trash"></i></span></div>'+
            '</div>'
          );
        }

        function deleteShareHolder(id){
          $('#shareHolder'+id).parent().parent().remove();
        }

        function addShareHolder(value=""){
          cptShareHolder++;
          $('.shareHolderBox').append(
            '<div class="form-group row">' +
            '<div class="col-sm-11">' +
            '<input placeholder="Entrer le nom d\'un actionnaire" class="form-control" name="shareHolders[]" id="shareHolder'+ cptShareHolder +'" value="' + value + '">' +
            '</div>' +
            '<div class="col-md-1 text-danger" style="position: relative"><span onclick="deleteShareHolder('+ cptShareHolder +')" style=" position: absolute;top: 50%;transform: translateY(-50%); cursor: pointer"><i class="fa fa-trash"></i></span></div>'+
            '</div>'
          );
        }

        $( document ).ready(function() {

            $('.select-search').select2({
                width: "100%",
            });

            $('#loadData').click(function(){
                $.ajax({
                    url: "{{  url('admin/json/wikipedia') }}/"+$('#wikipedia').val(),
                    context: document.body
                }).done(function(data) {
                    data = $.parseJSON(data);
                    $.each(data, function( index, value ) {
                        addInfo(index, value);
                    });
                    $('#wikipediaModal').modal('hide');
                }).fail(function(data){
                    alert('Cette page wikipédia n\est pas accessible !')
                });
            });

            @if(!empty(old('infoDatas')))
                @foreach(old('infoDatas') as $k => $infoData)
                    addInfo("{{ old('infoNames')[$k] }}", "{{ $infoData }}");
                @endforeach
            @endif

            @if(!empty(old('shareHolders')))
                @foreach(old('shareHolders') as $shareHolder)
                    addShareHolder("{{ $shareHolder }}");
                @endforeach
            @endif
        });
    </script>

@endsection

resources/views/back/industry/companies/index.blade.php
@extends('back.layout.default', ['navLink' => 'industry.companies'])

@section('title', 'Entreprises')

@section('header')
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><span class="font-weight-semibold">
                    <a href="{{ route('admin.industry.companies.index') }}">Entreprises</a> @if(!empty($company))>> <span class="badge badge-dark">{{ $company->name }}</span>@endif
                </span>
            </h4>
        </div>

        <div class="header-elements d-none text-center text-md-left mb-3 mb-md-0">
            <a href="{{ route('admin.industry.companies.create') }}" class="btn bg-danger-400"><i class="fa fa-plus-circle"></i> Créer une entreprise</a>
        </div>
    </div>
@endsection
@section('content')

    @if(Session::has('adminInsdustryCompaniesDeletedSuccess'))
        <div class="alert bg-success text-white alert-styled-right alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
            <span class="font-weight-semibold">Super!</span> Cette entreprise n'existe maintenant plus !
        </div>
    @elseif(Session::has('adminInsdustryCompaniesCreatedSuccess'))
        <div class="alert bg-success text-white alert-styled-right alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
            <span class="font-weight-semibold">Super!</span> Vous venez de créer avec succès une entreprise
        </div>
    @elseif(Session::has('adminInsdustryCompaniesUpdatedSuccess'))
        <div class="alert bg-success text-white alert-styled-right alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
            <span class="font-weight-semibold">Super!</span> Vous venez de mettre à jour une entreprise
        </div>
    @endif

    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Liste des entreprises</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            Les <code>Entreprises</code> sont affichés ici, en cliquant sur le petit bouton à droite tu pourras directement les gèrer. Pour l'instant les options disponibles sont : <code>créer</code>,  <code>modifier</code>, <code>supprimer</code> !
        </div>

        <table class="table datatableItems">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Logo</th>
                    <th>Nom</th>
                    <th>Holding</th>
                    <th>Appartient à une holding ?</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
            @foreach($companies as $company)
                <tr>
                    <td>{{ $company->id }}</td>
                    <td><img src="{{ url('uploads/company/'.$company->image) }}" alt="Logo {{ $company->image }}" style="max-width: 150px;max-height: 50px"></td>
                    <td>{{ $company->name }}</td>
                    <td>@if($company->isHolding()) <span class="badge badge-success">Oui</span> @else <span class="badge badge-danger">Non</span> @endif</td>
                    <td>@if($company->parent) <a href="{{ route('admin.industry.companies.show', $company->parent->id) }}">{{ $company->parent->name }}</a> @else <span class="badge badge-danger">Non</span> @endif</td>
                    <td class="text-center">
                        <div class="list-icons">
                            <div class="dropdown">
                                <a href="#" class="list-icons-item" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="{{ route('admin.industry.companies.edit', $company) }}" class="dropdown-item"><i class="icon-pencil4"></i> Modifier</a>
                                    @if($company->isHolding())
                                    <a href="{{ route('admin.industry.companies.show', $company) }}" class="dropdown-item"><i class="icon-tree6"></i> Voir les entreprises</a>
                                    @endif
                                    <a data-toggle="modal" data-target="#modalItem" onClick="deleteItem({{ $company->id }})" href="javascript:void(0)" class="dropdown-item"><i class="icon-trash"></i> Supprimer</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div id="modalItem" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h5 class="modal-title"><i class="icon-trash"></i> &nbsp;Supprimer une entreprise</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <div class="modal-body">
                    <div class="alert alert-danger alert-dismissible alert-styled-left border-top-0 border-bottom-0 border-right-0">
                        <span class="font-weight-semibold">Attention!</span> Vous ne pourrez pas revenir en arrière.
                        <button type="button" class="close" data-dismiss="alert">×</button>
                    </div>

                    <h6 class="font-weight-semibold"><i class="icon-info3 mr-2"></i> Suppresion non réversible</h6>
                    <p>En supprimant cette entreprise, toutes les données relatives à celle-ci seront perdues.</p>
                </div>

                <div class="modal-footer">
                    <button class="btn btn-link" data-dismiss="modal"><i class="icon-cross2 font-size-base mr-1"></i> Annuler</button>
                    {!! BootForm::open(['method' => 'DELETE']) !!}
                    <button class="btn bg-danger"><i class="icon-checkmark3 font-size-base mr-1"></i> Supprimer</button>
                    {!! BootForm::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('admin_assets/js/pages/datatablesDefault.js') }}"></script>
    <script type="text/javascript">
        function deleteItem(id){
            $('#modalItem form').attr('action', '{{ route('admin.industry.companies.index') }}/'+id);
        }
    </script>
@endsection