routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('home');
Route::get('/home2', 'PageController@index2')->name('home2');
Route::get('/about', 'PageController@about')->name('about');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::get('/search', 'SearchController@search')->name('search');
Route::get('/search/{search}/{unsetKeyword}', 'SearchController@unsetKeyword')->name('search.unsetKeyword');
Route::get('/json/companies.json', 'SearchController@jsonCompanies')->name('search.companies.json');


Route::prefix('login')->group(function () {
    Route::post('/', 'LoginController@index')->name('login.post');
    Route::get('register', 'LoginController@register')->name('login.register');
    Route::get('forgot', 'LoginController@forgot')->name('login.forgot');
    Route::post('forgot', 'LoginController@postForgot')->name('login.forgot.post');
    Route::get('reset/{email}/{token}', 'LoginController@reset')->name('login.reset');
    Route::post('reset/{email}/{token}', 'LoginController@postReset')->name('login.reset.post');
    Route::post('register', 'LoginController@postRegister')->name('login.register.post');
    Route::get('logout', 'LoginController@logout')->name('login.logout');
    Route::get('facebook', 'LoginController@redirectToFacebook')->name('login.facebook');
    Route::get('facebook/callback', 'LoginController@handleProviderCallback')->name('login.facebook.redirect');
});

Route::prefix('blog')->group(function(){
    Route::get('/', 'BlogController@index')->name('blog.index');
    Route::get('{slug}', 'BlogController@show')->name('blog.show');
    Route::post('{slug}', 'BlogController@postComment')->name('blog.comment.post');
});

Route::prefix('admin')->middleware('admin')->as('admin.')->group(function () {
    Route::get('/', 'Admin\PageController@index')->name('index');
    Route::resource('users', 'Admin\UserController');

    Route::prefix('blog')->as('blog.')->group(function () {
        Route::resource('articles', 'Admin\Blog\ArticleController');
        Route::resource('categories', 'Admin\Blog\CategoryController');
        Route::resource('tags', 'Admin\Blog\TagController');
        Route::resource('comments', 'Admin\Blog\CommentController')->except('create', 'store');
    });

    Route::prefix('categorization')->as('categorization.')->group(function () {
        Route::resource('domains', 'Admin\Categorization\DomainController')->except('show');
        Route::resource('activity_areas', 'Admin\Categorization\ActivityAreaController')->except('show');
    });

    Route::prefix('industry')->as('industry.')->group(function () {
        Route::resource('companies', 'Admin\Industry\CompanyController');
        Route::resource('comments', 'Admin\Industry\CommentController');
    });

    Route::prefix('question')->as('question.')->group(function () {
        Route::resource('domains', 'Admin\Question\DomainController');
        Route::resource('activity_areas', 'Admin\Question\ActivityAreaController');
    });

    Route::get('algorithme', 'Admin\PageController@algorithme')->name('algorithme');
    Route::post('algorithme', 'Admin\PageController@postAlgorithme')->name('algorithme.post');

    Route::resource('icons', 'Admin\IconController')->except('show');

    Route::prefix('json')->as('json.')->group(function () {
        Route::get('tags', 'Admin\Blog\TagController@json')->name('tags');
        Route::get('wikipedia/{object}', 'Admin\PageController@wikipediaApi')->name('wikiApi');
    });

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role', 'xp', 'fb_id', 'avatar',
    ];

    private $imagePath = 'uploads/avatar';

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function articles(){
        return $this->hasMany('App\Models\Blog\Article');
    }

    public function isAdmin(){
        if($this->role == -1) return true;
        return false;
    }

    public function getImage(){
        return url($this->imagePath.'/'.$this->avatar);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\File;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('back.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('back.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'username' => 'required|min:4|alpha_dash|unique:users,name',
            'email' => 'required|email|unique:users',
            'pass1' => 'required|min:6',
            'pass2' => 'required|same:pass1',
            'avatar' => 'image|max:2048|dimensions:min_width:150,min_height:150',
            'role' => 'required|numeric|between:-1,0',
            'fb_id' => '',
            'xp' => 'min:0'
        ]);

        $user = new User();
        $user->name = $request->input('username');
        $user->email = $request->input('email');
        $user->password = Hash::make($request->input('pass1'));
        $user->role = $request->input('role');
        if(!empty($request->input('xp'))) $user->xp = $request->input('xp');
        $user->remember_token = $request->input('_token');
        if(is_numeric($request->input('fb_id'))) $user->fb_id = $request->input('fb_id');

        if($request->hasFile('avatar')){
            $image = Image::make($request->file('avatar'))->fit(150,150);
            $nameExist = true;
            while($nameExist){
                $avatarName = 'a_'.str_random(rand(6,12)).'.jpg';
                if ( !file_exists( public_path('uploads/avatar/'.$avatarName)) ) $nameExist = false;
            }
            $image->save('uploads/avatar/'.$avatarName);
            $user->avatar = $avatarName;
        }

        $user->save();

        return redirect()->route('admin.users.index')->with('adminUserCreatedSuccess', true);
    }

    /**
     * Log-in as user.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        Auth::login($user);
        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $eUser = User::findOrFail($id);
        return view('back.users.edit', compact('eUser'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $uUser = User::findOrFail($id);
        $request->validate([
            'name' => ['required', 'min:4', 'alpha_dash', Rule::unique('users')->ignore($uUser->id)],
            'email' => ['required', 'email', Rule::unique('users')->ignore($uUser->id)],
            'pass1' => 'nullable|min:6',
            'pass2' => 'same:pass1',
            'avatar' => 'nullable|image|max:2048|dimensions:min_width:150,min_height:150',
            'role' => 'required|numeric|between:-1,0',
            'fb_id' => 'nullable',
            'xp' => 'nullable|numeric|min:0'
        ]);


        $uUser->name = $request->input('name');
        $uUser->email = $request->input('email');
        if(!empty($request->input('pass1'))) $uUser->password = Hash::make($request->input('pass1'));
        $uUser->role = $request->input('role');
        if(!empty($request->input('xp'))) $uUser->xp = $request->input('xp');
        $uUser->remember_token = $request->input('_token');
        if(is_numeric($request->input('fb_id'))) $uUser->fb_id = $request->input('fb_id');

        if($request->hasFile('avatar')){
            if ( file_exists( public_path('uploads/avatar/'.$uUser->avatar)) ){
                File::delete(public_path('uploads/avatar/'.$uUser->avatar));
            }
            $image = Image::make($request->file('avatar'))->fit(150,150);
            $nameExist = true;
            while($nameExist){
                $avatarName = 'a_'.str_random(rand(6,12)).'.jpg';
                if ( !file_exists( public_path('uploads/avatar/'.$avatarName) ) ) $nameExist = false;
            }
            $image->save('uploads/avatar/'.$avatarName);
            $uUser->avatar = $avatarName;
        }

        $uUser->save();

        return redirect()->route('admin.users.index')->with('adminUserUpdatedSuccess', true);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        if($user->id != Auth::user()->id){
            // TODO: Suppresion de l'avatar, des commentaires ...
            $user->delete();
            return redirect()->back()->with('adminUserDeletedSuccess', true);
        }

        return redirect()->back()->with('adminUserDeletedError', true);
    }
}

resources/views/back/users/create.blade.php
@extends('back.layout.default', ['navLink' => 'users'])

@section('title', 'Créer un utilisateur')

@section('header')
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><span class="font-weight-semibold">Créer un utilisateur</span></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
@endsection
@section('content')

    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Créer un utilisateur</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            Créer un <code>Utilisateur</code> est très simple, il suffit de renseigner tout les champs du formulaire, à savoir que le champs fb_id sert seulement si l'on possède l'id de l'utilisateur que l'applicaton retourne !
        <hr>
        {!! BootForm::open(['enctype' => 'multipart/form-data', 'url' => route('admin.users.store')]) !!}

            {!! BootForm::text('username', false, null, ['placeholder' => 'Nom d\'utilisateur']) !!}
            {!! BootForm::email('email', false, null, ['placeholder' => 'E-mail']) !!}
            {!! BootForm::password('pass1', false, ['placeholder' => 'Mot de passe']) !!}
            {!! BootForm::password('pass2', false, ['placeholder' => 'Confirmer le mot de passe']) !!}
            {!! BootForm::number('xp', false, null, ['placeholder' => 'Nombre de point d\'XP (numérique)', 'min' => 0]) !!}
            {!! BootForm::select('role', false, [0 => 'Utilisateur', -1 => 'Administrateur']) !!}
            {!! BootForm::text('fb_id', false, null, ['placeholder' => 'ID Facebook']) !!}
            <hr>
            {!! BootForm::file('avatar', 'Avatar', ['placeholder' => 'Avatar']) !!}
            <hr>
            <div class="text-right">
                <button type="submit" class="btn btn-lg btn-primary">Créer</button>
            </div>
        {!! BootForm::close() !!}
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript">
        $('.form-control-uniform').uniform();
    </script>
@endsection

resources/views/back/users/edit.blade.php
@extends('back.layout.default', ['navLink' => 'users'])

@section('title', 'Modifier un utilisateur')

@section('header')
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><span class="font-weight-semibold">Modifier un utilisateur</span></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
@endsection
@section('content')


    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Modifier l'utilisateur: {{ $eUser->name }}</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            Modifier <code>{{ $eUser->name }}</code> est très simple, il suffit de renseigner tout les champs du formulaire ci-dessous. Pour changer d'avatar il suffit simplement de choisir une photo avec le champs du formulaire en question !
            Si vous ne souhaitez pas modifier le mot de passe ou l'avatar, il suffit de laisser les champs vides !
        <hr>
        {!! BootForm::open(['enctype' => 'multipart/form-data', 'url' => route('admin.users.update', $eUser), 'model' => $eUser, 'method' => 'PUT']) !!}
            {!! BootForm::text('name', 'Nom d\'utilisateur', null, ['placeholder' => 'Nom d\'utilisateur']) !!}
            {!! BootForm::email('email', 'Email', null, ['placeholder' => 'E-mail']) !!}
            {!! BootForm::number('xp', 'Nombre d\'XP', null, ['placeholder' => 'Nombre de point d\'XP (numérique)', 'min' => 0]) !!}
            {!! BootForm::select('role', 'Rôle', [0 => 'Utilisateur', -1 => 'Administrateur']) !!}
            {!! BootForm::text('fb_id', 'Facebook ID', null, ['placeholder' => 'ID Facebook']) !!}
            <hr>
            {!! BootForm::file('avatar', 'Avatar', ['placeholder' => 'Avatar']) !!}
            {!! BootForm::password('pass1', false, ['placeholder' => 'Mot de passe']) !!}
            {!! BootForm::password('pass2', false, ['placeholder' => 'Confirmer le mot de passe']) !!}
            <hr>
            <div class="text-right">
                <button type="submit" class="btn btn-lg btn-primary">Modifier</button>
            </div>
        {!! BootForm::close() !!}
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('admin_assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript">
        $('.form-control-uniform').uniform();
    </script>
@endsection

resources/views/back/users/index.blade.php
@extends('back.layout.default', ['navLink' => 'users'])

@section('title', 'Utilisateurs')

@section('header')
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><span class="font-weight-semibold">Utilisateurs</span></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        <div class="header-elements d-none text-center text-md-left mb-3 mb-md-0">
            <a href="{{ route('admin.users.create') }}" class="btn bg-danger-400"><i class="fa fa-plus-circle"></i> Créer un utilisateur</a>
        </div>
    </div>
@endsection
@section('content')

    @if(Session::has('adminUserDeletedError'))
        <div class="alert bg-danger text-white alert-styled-right alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
            <span class="font-weight-semibold">Oups!</span> Vous ne pouvez pas supprimer votre propre compte <a href="#" class="alert-link">Réessayer avec un autre compte</a>.
        </div>
    @elseif(Session::has('adminUserDeletedSuccess'))
        <div class="alert bg-success text-white alert-styled-right alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
            <span class="font-weight-semibold">Super!</span> Ce méchant utilisateur a maintenant été supprimé
        </div>
    @elseif(Session::has('adminUserCreatedSuccess'))
        <div class="alert bg-success text-white alert-styled-right alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
            <span class="font-weight-semibold">Super!</span> Vous venez de créer avec succès un nouveau utilisateur
        </div>
    @elseif(Session::has('adminUserUpdatedSuccess'))
        <div class="alert bg-success text-white alert-styled-right alert-dismissible">
            <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
            <span class="font-weight-semibold">Super!</span> Vous venez de mettre à jour le profil d'un utilisateur
        </div>
    @endif

    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Liste des utilisateurs</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
            Les <code>Utilisateurs</code> sont affichés ici, en cliquant sur le petit bouton à droite tu pourras directement les gèrer. Pour l'instant les options disponibles sont : <code>créer</code>, <code>se connecter</code>, <code>modifier</code>, <code>supprimer</code> !
        </div>

        <table class="table datatableUsers">
            <thead>
            <tr>
                <th>Nom</th>
                <th>E-mail</th>
                <th>FB</th>
                <th>XP</th>
                <th>Role</th>
                <th>Inscrit le</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $tableUser)
                <tr>
                    <td>{{ $tableUser->name }}</td>
                    <td><a href="mailto:{{ $tableUser->email }}">{{ $tableUser->email }}</a></td>
                    <td>{{ $tableUser->fb_id }}</td>
                    <td>{{ $tableUser->xp }}</td>
                    <td>
                        @switch($tableUser->role)
                            @case(-1)
                            <span class="badge badge-dark">Administrateur</span>
                            @break

                            @case(0)
                            <span class="badge badge-primary">Utilisateur</span>
                            @break

                            @default
                            <span class="badge badge-warning">Non défini</span>
                        @endswitch
                    </td>
                    <td>{{ $tableUser->created_at->format('d/m/Y') }}</td>
                    <td class="text-center">
                        <div class="list-icons">
                            <div class="dropdown">
                                <a href="#" class="list-icons-item" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="{{ route('admin.users.show', $tableUser) }}" class="dropdown-item"><i class="icon-key"></i> Se connecter</a>
                                    <a href="{{ route('admin.users.edit', $tableUser) }}" class="dropdown-item"><i class="icon-pencil4"></i> Modifier</a>
                                    <a data-toggle="modal" data-target="#modalDeleteUser" onClick="deleteUser({{ $tableUser->id }})" href="javascript:void(0)" class="dropdown-item"><i class="icon-trash"></i> Supprimer</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div id="modalDeleteUser" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h5 class="modal-title"><i class="icon-trash"></i> &nbsp;Supprimer un utilisateur</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <div class="modal-body">
                    <div class="alert alert-danger alert-dismissible alert-styled-left border-top-0 border-bottom-0 border-right-0">
                        <span class="font-weight-semibold">Attention!</span> Vous ne pourrez pas revenir en arrière.
                        <button type="button" class="close" data-dismiss="alert">×</button>
                    </div>

                    <h6 class="font-weight-semibold"><i class="icon-info3 mr-2"></i> Suppresion de l'utilisateur</h6>
                    <p>Toutes les données associées à ce compte seront supprimées tels que : ses photos, ses commentaires ainsi que toutes autres participations.</p>

                    <hr>
                </div>

                <div class="modal-footer">
                    <button class="btn btn-link" data-dismiss="modal"><i class="icon-cross2 font-size-base mr-1"></i> Annuler</button>
                    {!! BootForm::open(['method' => 'DELETE']) !!}
                        <button class="btn bg-danger"><i class="icon-checkmark3 font-size-base mr-1"></i> Supprimer</button>
                    {!! BootForm::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('admin_assets/js/pages/datatablesUsers.js') }}"></script>
    <script type="text/javascript">
        function deleteUser(id){
            $('#modalDeleteUser form').attr('action', '{{ route('admin.users.index') }}/'+id);
        }
    </script>
@endsection